### ISSUE TITLE
NoClassDefFoundError: weka.classifiers.functions.MultilayerPerceptron$ControlPanel

### ISSUE THREAD

**Issue by mickeN89** [MeiyappanKannappa/Weka-Android#1]
I've got this trying to load preconfig. model in android running this:
classifier = (Classifier)weka.core.SerializationHelper.read(assetManager.open("multilayer.model"));

I'm I doing something wrong? new to this..

**Comment by MeiyappanKannappa** [comment]
Hi,

Could you provide more details on your issue. Are you getting any exception or error?

**Comment by mickeN89** [comment]
Its as mentioned when I try to instantiate the classifier but getting an 
Fatal Exception




På 13 december 2017 10:08:40 Karthik Meiyappan <notifications@github.com> 
skrev:

**Comment by MeiyappanKannappa** [comment]
I can look on this weekend. But please see the below link meanwhile, it seems multilayer perceptron has some issues with android.

https://stackoverflow.com/questions/38026614/weka-classnotfoundexception-on-android

**Comment by mickeN89** [comment]
This seems to be it, SimpleLogistics.model working
thank you
